create database customer_behavior;
use customer_behavior;
select * from `customer`;

select * from customer limit 20;

#1: what is Total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

#2: Which customer used a discount but still spentmore than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

#3: Which are the top 5 products with higest verage review rating?
select item_purchased, round(avg(review_rating),2) as "Average Review Rating"
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

#4: compare the average purcahse amount between the satndard and express shipping?
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('standard','Express')
group by shipping_type;

#5: Do suscribed customer spend more? compare verage spend and total revenue between subscribers and non-subscribers ?
select subscription_status,
count(customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

#6: Which 5 product have the highest percentage of purchase with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then  1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#7: Segment customer into new returning and loyal based on thire total 
#number pf previous purchase , and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 THEN 'NEW'
     when previous_purchases between 2 and 10 THEN 'Returning'
     else 'Loyal'
     end as customer_segment
from customer
)

select customer_segment, count(*) as  "number of customers"
from customer_type
group by customer_segment;

#8: What are the top 3 most purcahsed product within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

#9: Are customer who are repeate buyers (more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

#10 What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;






